[package]
name = "mr"
version = "0.1.0"
authors = ["Robbie Pitts <me@robbie-pitts.com>"]
edition = "2018"

[[bin]]
name = "mr-util"
path = "src/main.rs"

[dependencies]
structopt = { version = "0.3" }
