[package]
name = "mr"
version = "0.1.0"
authors = ["Robbie Pitts <me@robbie-pitts.com>"]
edition = "2018"

[[bin]]
name = "mr-util"
path = "src/main.rs"

[dependencies]
glob = "0.3"
json = "0.12.4"
structopt = "0.3"
